#this file is for travis-ci to tell it how to handle our project
language: node
sudo: required
#this tells to give authority of sudo level

services:
  - docker
#this tells to give docker copy

before_install:
  - docker build -t khuzama98/simple-react-app -f Dockerfile.dev .

script:
  - docker run khuzama98/simple-react-app npm run test -- --coverage
#this tells to run test and -- --coverage is to tell npm to return the status code
#of test and close itself otherwise npm won't closes it's self and stays open and
#travis won't know did the test pass or fail
